name: fe_test_task
description: A quick test project with jsonplaceholder.typicode oposts API

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  animations: ^2.0.2
  auto_route: ^3.0.4

  connectivity_plus: ^2.0.2
  cupertino_icons: ^1.0.2

  dartz: 0.10.0-nullsafety.2

  equatable: ^2.0.3

  flutter:
    sdk: flutter

  google_fonts: ^2.1.0

  http: ^0.13.3

  json_annotation: ^4.3.0

  moor: ^4.5.0
  moor_flutter: ^4.0.0

  path: ^1.8.0
  path_provider: ^2.0.5
  provider: ^6.0.1

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  json_serializable: ^6.0.1

  mocktail: ^0.1.4
  moor_generator: ^4.3.2

flutter:
  uses-material-design: true
